
name: 'SemVer Tag on Main Merge'
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  pull-requests: read
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  semver-tag:
    name: 'Tag Repository with SemVer'
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse the SemVer label
        id: label
        uses: UKHomeOffice/match-label-action@a8e8e2690df0a1f72550875a29a73574fdefe5ad
        with:
          labels: minor,major,patch
          mode: singular

      - name: Calculate SemVer value
        id: calculate
        uses: UKHomeOffice/semver-calculate-action@fd7e1629eda3b5d3cd037d4145d49db12a352c8e
        with:
          increment: ${{ steps.label.outputs.matchedLabels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Repository
        uses: UKHomeOffice/semver-tag-action@c95496307c40862d4e1659b47b7387f8a254a2d1
        with:
          tag: ${{ steps.calculate.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}